<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="footer"
    errors="1" failures="0" hostname="" id="" package="footer" skipped="0"
    tests="1" time="0.01300" timestamp="Thu, 04 May 2017 06:23:30 GMT">
  
    <testcase name="footer footer-links" time="0.01300" assertions="0">
    </testcase>
      <system-err>
          Error while running [Footer / footer footer-links]:

  ReferenceError: test1 is not defined
    at Object.footer footer-links (C:\BankOfBrands\Automation_scripts\tests\footer.js:19:63)
    at Module.call (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\balakrishna.vavilala\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
      </system-err>
  
  
  </testsuite>
</testsuites>
